"""Add initial tables

Revision ID: 3c769bfd7e90
Revises: b567ade113ab
Create Date: 2022-10-02 18:43:54.128596

"""


# revision identifiers, used by Alembic.
revision = '3c769bfd7e90'
down_revision = 'b567ade113ab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
